name: Node CI/CD Workflow
on: 
  push:
    branches: [ main ]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2
        name: Check out repository      
      
      - uses: actions/setup-node@v2
        name: Use Node.js
        with:
         node-version: '14.x'                
     
      - run: npm install
        name: Install dependencies
      
      - run: npm test        
        name: Run test        
        
  deploy:    
    runs-on: ubuntu-latest
    needs: [build]    
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        name: Deploy to Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
     
      - uses: appleboy/telegram-action@master
        name: send telegram message on push
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
